export const faIconList: string[] = [
  'fa fa-android',
  'fa fa-amazon',
  'fa fa-bluetooth-b',
  'fa fa-btc',
  'fa fa-chrome',
  'fa fa-edge',
  'fa fa-facebook-square',
  'fa fa-firefox',
  'fa fa-github',
  'fa fa-google-wallet',
  'fa fa-instagram',
  'fa fa-linkedin-square',
  'fa fa-linux',
  'fa fa-paypal',
  'fa fa-safari',
  'fa fa-skype',
  'fa fa-twitter',
  'fa fa-whatsapp',
];
